const barcelona = {
    titulo: 'Descubre Barcelona: La joya de Cataluña',
    subtitulo: 'Sumérgete en la historia, cultura y belleza de esta vibrante ciudad',
    parrafo: "Bienvenidos a Barcelona, una ciudad cautivadora que combina a la perfección la riqueza histórica con una atmósfera moderna y dinámica. Situada en la región de Cataluña, al noreste de España, Barcelona es conocida por su arquitectura icónica, su vibrante escena artística, su deliciosa gastronomía y sus hermosas playas mediterráneas. <br> <br> Nuestro recorrido por Barcelona comienza en su corazón histórico: el Barrio Gótico.Perdiéndote en sus estrechas calles empedradas, descubrirás impresionantes edificios medievales, iglesias antiguas y encantadoras plazas llenas de vida.No puedes dejar de visitar la majestuosa Catedral de Barcelona, un magnífico ejemplo de la arquitectura gótica.<br> <br> A medida que te adentras en la ciudad, te maravillarás con las obras maestras arquitectónicas de Antoni Gaudí, uno de los más grandes exponentes del modernismo catalán.La Sagrada Familia, su obra maestra inacabada, te dejará sin palabras con su diseño único y sus detalles ornamentales.Otros tesoros de Gaudí incluyen el Parque Güell, con sus coloridos mosaicos y vistas panorámicas de la ciudad, y la Casa Batlló, un edificio modernista que parece salido de un cuento de hadas.<br> <br> Barcelona también es famosa por su pasión por el fútbol.Si eres amante de este deporte, no puedes perderte el Camp Nou, el estadio del FC Barcelona.Sumérgete en la atmósfera apasionada de un partido y descubre la historia del club en su museo.<br> <br> Pero Barcelona no se trata solo de arquitectura y deporte.La ciudad cuenta con una escena cultural bulliciosa, con una gran variedad de museos, galerías de arte y eventos culturales.El Museo Picasso alberga una impresionante colección de obras del famoso pintor español, mientras que el MACBA y el CCCB son espacios dedicados al arte contemporáneo y la cultura urbana.<br> ",
    precio: '💸El precio apoximado de boletos es de 500 euros.'
}

const roma = {
    titulo: 'Roma: Tesoros eternos en la Ciudad Eterna',
    subtitulo: 'Sumérgete en la grandeza histórica, el arte y la cultura de la capital italiana',
    parrafo: "Bienvenidos a Roma, una ciudad que respira historia y que te transportará a través de los siglos. Conocida como la Ciudad Eterna, Roma es el hogar de una riqueza inigualable de monumentos antiguos, arte renacentista y una cultura vibrante que te cautivará desde el primer momento. <br> <br> Nuestro viaje por Roma comienza en el corazón de la antigua Roma: el Coliseo. Este imponente anfiteatro es una de las maravillas arquitectónicas más emblemáticas del mundo y te dejará sin aliento con su magnificencia. Imagina los emocionantes combates de gladiadores y las representaciones teatrales que una vez tuvieron lugar en este legendario lugar.<br> <br> A pocos pasos del Coliseo, descubrirás el Foro Romano, el centro político y social de la antigua Roma. Recorre las ruinas de antiguos templos, arcos triunfales y basílicas, y déjate llevar por la majestuosidad de este lugar lleno de historia. <br> <br> Continuando nuestro recorrido, nos dirigimos al Vaticano, el enclave independiente más pequeño del mundo y el corazón espiritual del catolicismo. La Basílica de San Pedro, con su icónica cúpula diseñada por Miguel Ángel, te impresionará con su belleza y esplendor. No olvides visitar también los Museos Vaticanos, donde podrás admirar una impresionante colección de arte, incluyendo la famosa Capilla Sixtina, con sus frescos creados por grandes artistas renacentistas.<br> <br>     Roma también es conocida por sus encantadoras plazas y fuentes. La Piazza Navona, con su arquitectura barroca y su famosa Fuente de los Cuatro Ríos, te invita a relajarte y disfrutar del ambiente romano. La Fontana di Trevi, la fuente más famosa de la ciudad, es un lugar de visita obligada para lanzar una moneda y asegurarte de volver a Roma en el futuro.<br> ",
    precio: '💸 El precio apoximado de boletos es de 600 euros.'
}

const paris = {
    titulo: 'París: La Ciudad de la Luz y el Romance',
    subtitulo: 'Explora la elegancia, la cultura y el encanto de la capital francesa',
    parrafo: "Bienvenidos a París, una ciudad que ha cautivado a visitantes de todo el mundo con su belleza, elegancia y romance. Conocida como la Ciudad de la Luz, París ofrece una mezcla única de historia, arte, cultura y gastronomía que la convierte en un destino verdaderamente inolvidable.    <br> <br>    Nuestro viaje por París comienza en el corazón de la ciudad, en la icónica Torre Eiffel. Esta estructura emblemática, construida para la Exposición Universal de 1889, te brindará una vista panorámica impresionante de la ciudad. Ya sea que decidas subir a la cima o simplemente admirarla desde el suelo, la Torre Eiffel es un símbolo inconfundible de París.    <br> <br>    Continuando nuestro recorrido, nos adentramos en el encantador barrio de Montmartre, conocido por su atmósfera bohemia y su belleza pintoresca. Explora sus estrechas calles empedradas y llega a la imponente Basílica del Sagrado Corazón, que ofrece vistas panorámicas de la ciudad. No olvides visitar el famoso cabaret Moulin Rouge y disfrutar de un espectáculo lleno de energía y glamour.    <br> <br>    El siguiente destino es el Louvre, uno de los museos más grandes y famosos del mundo. Admira obras maestras como la Mona Lisa y la Venus de Milo, mientras te maravillas con la grandiosidad del Palacio del Louvre, una joya arquitectónica en sí misma. Recorrer sus galerías es sumergirse en la historia del arte y la cultura.    <br> <br>    Cruzar el río Sena nos lleva al encantador barrio de Saint-Germain-des-Prés, conocido por sus librerías, cafés históricos y ambiente intelectual. Sumérgete en la cultura parisina mientras disfrutas de un café en el famoso Café de Flore o exploras las tiendas de moda y galerías de arte de la zona.    <br>",
    precio: '💸 El precio apoximado de boletos es de 700 euros.'
}

const londres = {
    titulo: 'Londres: Descubre la magia de la Ciudad del Támesis',
    subtitulo: 'Sumérgete en la historia, la diversidad y la energía de la capital británica',
    parrafo: "Bienvenidos a Londres, una ciudad vibrante que fusiona su rica historia con una escena contemporánea y diversa. Conocida como la Ciudad del Támesis, Londres te cautivará con su encanto, su patrimonio cultural y su espíritu cosmopolita.    <br> <br>    Nuestro recorrido por Londres comienza en el icónico Palacio de Buckingham, la residencia oficial de la Reina de Inglaterra. Si tienes suerte, podrás presenciar el cambio de guardia, una ceremonia tradicional llena de pompa y color. Desde allí, podrás pasear por el cercano Parque de St. James y disfrutar de la serenidad de sus jardines.    <br> <br>    Continuando nuestro viaje, llegamos al corazón histórico de Londres: la Torre de Londres. Este emblemático castillo es testigo de siglos de historia y alberga las joyas de la Corona británica. Explora sus muros fortificados y descubre las historias de intrigas, traiciones y misterios que envuelven a este lugar.    <br> <br>    Cruzando el Tower Bridge, uno de los símbolos más reconocidos de la ciudad, nos adentramos en el bullicioso Southbank. Aquí encontrarás una amplia gama de atracciones culturales, como el Tate Modern, un museo de arte contemporáneo, y el London Eye, una noria gigante que ofrece vistas panorámicas impresionantes de la ciudad.    <br> <br>    Londres es también famosa por sus museos de clase mundial. El Museo Británico, con su impresionante colección de artefactos y antigüedades de todo el mundo, es un tesoro imperdible. No puedes perderte la oportunidad de visitar el Museo de Historia Natural, con su famoso esqueleto de dinosaurio y su impactante colección de especímenes.    <br> ",
    precio: '💸 El precio apoximado de boletos es de 800 euros.'
}

export {
    barcelona,
    roma,
    paris,
    londres
};

// const { barcelona, roma, paris, londres } = require('./ciudades');

//ES6
// export { objeto1, objeto2 };
//import { objeto1, objeto2 } from './ciudades';